server:
  port: 8080

spring:
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    conten-type: text/html
    cache: false
#    check-template: true
#    check-template-location: true
#  mvc:
#    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB